namespace Rebirth.Common.Types
{
    public enum FieldType
    {
        DEFAULT = 0x0,
        SNOWBALL = 0x1,
        CONTIMOVE = 0x2,
        TOURNAMENT = 0x3,
        COCONUT = 0x4,
        OXQUIZ = 0x5,
        PERSONALTIMELIMIT = 0x6, // dungeon
        WAITINGROOM = 0x7,
        GUILDBOSS = 0x8,
        LIMITEDVIEW = 0x9,
        MONSTERCARNIVAL = 0xA,
        MONSTERCARNIVALREVIVE = 0xB,
        ZAKUM = 0xC,
        ARIANTARENA = 0xD,
        DOJANG = 14,
        MONSTERCARNIVAL_S2 = 0xF,
        MONSTERCARNIVALWAITINGROOM = 0x10,
        COOKIEHOUSE = 0x11,
        BALROG = 0x12,
        BATTLEFIELD = 0x13,
        SPACEGAGA = 0x14,
        WITCHTOWER = 0x15,
        ARANTUTORIAL = 0x16,
        MASSACRE = 0x17,
        MASSACRE_RESULT = 0x18,
        PARTYRAID = 0x19,
        PARTYRAID_BOSS = 0x1A,
        PARTYRAID_RESULT = 0x1B,
        NODRAGON = 0x1C,
        DYNAMICFOOTHOLD = 29,
        ESCORT = 0x1E,
        ESCORT_RESULT = 0x1F,
        HUNTINGADBALLOON = 0x20,
        CHAOSZAKUM = 0x21,
        KILLCOUNT = 0x22,
        WEDDING = 0x3C,
        WEDDINGPHOTO = 0x3D,
        PROTECTSNOWMAN = 1000,
        SHOWABATH = 0x3E9,
        TUTORIAL = 0x3EA,
        PACHINKO = 0x3EB,
        BOATRACE = 0x3EC,
        BOATRACE2 = 0x3ED,
        LANGUAGESCHOOL = 1006,
        FISHING = 0x3EF,
        FISHINGKING = 1008,
        CNWEDDING = 0x3F1,
        CNPVPSHOOTINGONEMOB = 0x3F2,
        CNPVPSHOOTINGMANYMOB = 0x3F3,
        CNPVPJUMP = 0x3F4,
        HONTAIL = 0x3F5,
        NLCPQ = 0x3F6,
        TOKYOBOSS = 0x3F7,
        TOKYOBOSSPARTY = 0x3F8,
        ENTRUSTEDFISHING = 0x3F9,
        PUNCHPUNCH = 1018,
        CUBE = 0x23,

		// not nexon types
		CUSTOM_DUNGEONRAID_GOLEMTEMPLE = 10000,
        CUSTOM_COMMUNITYEVENT_RUSSIANROULETTE = 10010,
        CUSTOM_PINKBEAN = 10100,
        CUSTOM_AREA_BOSS = 10200,
    }
}
