namespace Rebirth.Common.Types
{
    public enum MarriageOps
    {
        MarriageReq_Propose = 0x0,
        MarriageReq_CancelPropose = 0x1,
        MarriageReq_Accept = 0x2,
        MarriageReq_BreakUp = 0x3,
        MarriageReq_Reserve = 0x4,
        MarriageReq_Invite = 0x5,
        MarriageReq_Invitation = 0x6,
        MarriageReq_Marry = 0x7,
        MarriageReq_Divorce = 0x8,
        MarriageReq_WishList = 0x9,
        MarriageReq_LoadReservation = 0xA,
        MarriageRes_Engaged = 0xB,
        MarriageRes_Married = 0xC,
        MarriageRes_BrokeUp = 0xD,
        MarriageRes_Divorced = 0xE,
        MarriageRes_ShowInvitation = 0xF,
        MarriageRes_ReservationDone = 0x10,
        MarriageRes_LoadReservationDone = 0x11,
        MarriageRes_WrongName = 0x12,
        MarriageRes_NotSameMap = 0x13,
        MarriageRes_RequesterNoEmptySlot = 0x14,
        MarriageRes_TargetNoEmptySlot = 0x15,
        MarriageRes_WrongGender = 0x16,
        MarriageRes_RequesterAlreadyEngaged = 0x17,
        MarriageRes_TargetAlreadyEngaged = 0x18,
        MarriageRes_RequesterAlreadyMarried = 0x19,
        MarriageRes_TargetAlreadyMarried = 0x1A,
        MarriageRes_RequesterAlreadyInProcess = 0x1B,
        MarriageRes_TargetAlreadyInProcess = 0x1C,
        MarriageRes_RequesterCanceled = 0x1D,
        MarriageRes_TargetRefused = 0x1E,
        MarriageRes_ReservationCanceled = 0x1F,
        MarriageRes_CantBreakupAfterReserve = 0x20,
        MarriageRes_NotEnoughMoney = 0x21,
        MarriageRes_WrongMarriageNo = 0x22,
        MarriageRes_ReservationFail = 0x23,
        MarriageRes_Unknown = 0x24,
    }
}
