namespace Rebirth.Common.Types
{
	public enum MobLeaveFieldType
	{
		MOBLEAVEFIELD_REMAINHP = 0,
		MOBLEAVEFIELD_ETC = 1,
		MOBLEAVEFIELD_SELFDESTRUCT = 2,
		MOBLEAVEFIELD_DESTRUCTBYMISS = 3,
		MOBLEAVEFIELD_SWALLOW = 4,
		MOBLEAVEFIELD_SUMMONTIMEOUT = 5,
	}
}
