namespace Rebirth.Common.Types
{
	public enum MoveAbility // enum $1F2FF3B4F3BEDE276FF7BCBB34BA068D
	{
		MOVEABILITY_STOP = 0,
		MOVEABILITY_WALK = 1,
		MOVEABILITY_WALK_RANDOM = 2,
		MOVEABILITY_JUMP = 3,
		MOVEABILITY_FLY = 4,
		MOVEABILITY_FLY_RANDOM = 5,
		MOVEABILITY_ESCORT = 6
	}
}
