namespace Rebirth.Common.Types
{
	public enum PortalType
	{
		STARTPOINT = 0x0,
		INVISIBLE = 0x1,
		VISIBLE = 0x2,
		COLLISION = 0x3,
		CHANGABLE = 0x4,
		CHANGABLE_INVISIBLE = 0x5,
		TOWNPORTAL_POINT = 0x6,
		SCRIPT = 0x7,
		SCRIPT_INVISIBLE = 0x8,
		COLLISION_SCRIPT = 0x9,
		HIDDEN = 0xA,
		SCRIPT_HIDDEN = 0xB,
		COLLISION_VERTICAL_JUMP = 0xC,
		COLLISION_CUSTOM_IMPACT = 0xD,
	}
}
