namespace Rebirth.Common.Types
{
	public enum SummonLeaveType
	{
		LEAVE_TYPE_UPDATE = 0x0,
		LEAVE_TYPE_SUMMONED_DEAD = 0x1,
		LEAVE_TYPE_MYSTERY = 0x2,
		LEAVE_TYPE_DEFAULT = 0x3,
		LEAVE_TYPE_LEAVE_FIELD = 0x4,
		LEAVE_TYPE_SELF_DESTRUCT = 0x5,
		LEAVE_TYPE_GABIOTA = 0x6,
		LEAVE_TYPE_ENTER_FORBIDEN_MAP = 0x7,
		LEAVE_TYPE_ENTER_EVENT_FIELD = 0x8,
		LEAVE_TYPE_USER_DEAD = 0x9,
		LEAVE_TYPE_ON_REMOVE = 0x0A,
		LEAVE_TYPE_TESLACOIL_ERROR = 0x0B,
		LEAVE_TYPE_NOT_ABLE_MULTIPLE = 0x0C,
		LEAVE_TYPE_DIDNT_SELFDESTRUCT = 0x0D,
		LEAVE_TYPE_SUMMONED_COUNT_OVER = 0x0E,
	}
}
