namespace Rebirth.Common.Types
{
    public enum UIWindow
    {
        UI_ITEM = 0x0,
        UI_EQUIP = 0x1,
        UI_STAT = 0x2,
        UI_SKILL = 0x3,
        UI_MINIMAP = 0x4,
        UI_KEYCONFIG = 0x5,
        UI_QUESTINFO = 0x6,
        UI_USERLIST = 0x7,
        UI_MESSENGER = 0x8,
        UI_MONSTERBOOK = 0x9,
        UI_USERINFO = 0x0A,
        UI_SHORTCUT = 0x0B,
        UI_MENU = 0x0C,
        UI_QUESTALARM = 0x0D,
        UI_PARTYHP = 0x0E,
        UI_QUESTTIMER = 0x0F,
        UI_QUESTTIMERACTION = 0x10,
        UI_MONSTERCARNIVAL = 17,
        UI_ITEMSEARCH = 0x12,
        UI_ENERGYBAR = 0x13,
        UI_GUILDBOARD = 20,
        UI_PARTYSEARCH = 0x15,
        UI_ITEMMAKE = 22,
        UI_CONSULT = 0x17,
        UI_CLASSCOMPETITION = 24,
        UI_RANKING = 0x19,
        UI_FAMILY = 0x1A,
        UI_FAMILYCHART = 0x1B,
        UI_OPERATORBOARD = 0x1C,
        UI_OPERATORBOARDSTATE = 0x1D,
        UI_MEDALQUESTINFO = 0x1E,
        UI_WEBEVENT = 0x1F,
        UI_SKILLEX = 32,
        UI_REPAIRDURABILITY = 0x21,
        UI_CHATWND = 0x22,
        UI_BATTLERECORD = 35,
        UI_GUILDMAKEMARK = 36,
        UI_GUILDMAKE = 37,
        UI_GUILDRANK = 38,
        UI_GUILDBBS = 39,
        UI_ACCOUNTMOREINFO = 0x28,
        UI_FINDFRIEND = 0x29,
        UI_DRAGONBOX = 42,
        UI_WNDNO = 0x2B,
        UI_UNRELEASE = 0x2C,
    }
}



